image: Visual Studio 2022
version: 1.0.{build}
configuration:
  - Release
before_build:
  - nuget restore
  - dotnet restore
assembly_info:
  patch: false
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: LiteNetLib.sln
test_script:
    - dotnet test m:1 "LiteNetLib\LiteNetLib.Tests\LiteNetLib.Tests.csproj" --configuration Release --no-build
artifacts:
  - path: LiteNetLib/bin/Release/net471
    name: LiteNetLib-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLib/bin/Release/netstandard2.0
    name: LiteNetLibStandard-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLib/bin/Release/netcoreapp3.1
    name: LiteNetLibNetCore-$(appveyor_build_version)
    type: Zip
