image: Visual Studio 2017
version: 0.9.{build}
configuration:
  - Release
before_build:
  - nuget restore
  - dotnet restore
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: LiteNetLib.sln
test:
  assemblies:
    - '**\*.Tests.dll'
artifacts:
  - path: LiteNetLib/bin/Release/net35
    name: LiteNetLib-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLib/bin/Release/netstandard2.0
    name: LiteNetLibStandard-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLib/bin/Release/netcoreapp2.1
    name: LiteNetLibNetCore-$(appveyor_build_version)
    type: Zip
