image: Visual Studio 2017
version: 0.8.{build}
configuration:
  - Release
before_build:
  - nuget restore
  - cd LiteNetLibStandard
  - dotnet restore
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: LiteNetLib.sln
test:
  assemblies:
    - '**\*.Test.dll'
    - '**\*.Tests.dll'
artifacts:
  - path: LiteNetLib/bin/Release
    name: LiteNetLib-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLibStandard/bin/Release
    name: LiteNetLibStandard-$(appveyor_build_version)
    type: Zip
  - path: LiteNetLibNetCore/bin/Release
    name: LiteNetLibNetCore-$(appveyor_build_version)
    type: Zip
